import { Inter } from 'next/font/google';
import "./globals.css";
import { SiWhatsapp } from "react-icons/si";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UML',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      {children}


      </body>
      </html>
  )
}
